### ISSUE TITLE
How to DevExpress to DLL?

### ISSUE THREAD

**Issue by dove457** [asfktz/autodll-webpack-plugin#124]
Hello,

I am trying to speed up development with Vue and Devexpress.

vue.config.js
```
module.exports = {
    configureWebpack: {
        plugins: [
            new AutoDllPlugin({
                context: __dirname,
                debug: true,
                inject: true,
                filename: '[name]_[hash].js',
                path: './dll',
                entry: {
                    vendor: ['vuex', 'vue', 'vue-router', 'devextreme'],
                },
            }),
        ]
    }
};
```

The error I get:
```
 vue-cli-service serve

 INFO  Starting development server...
AutoDllPlugin: is valid cache? false
AutoDllPlugin: cleanup
AutoDllPlugin: compile
[ ModuleNotFoundError: Module not found: Error: Can't resolve 'devextreme' in 'C:\Users\Dovydas\source\repos\Solution1\Program1\Client'
    at factory.create (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\webpack\lib\Compilation.js:821:10)
    at factory (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\webpack\lib\NormalModuleFactory.js:397:22)
    at resolver (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\neo-async\async.js:2825:7
    at C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\neo-async\async.js:6886:13
    at normalResolver.resolve (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
    at hook.callAsync (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
resolve 'devextreme' in 'C:\Users\Dovydas\source\repos\Solution1\Program1\Client'
  Parsed request is a module
  using description file: C:\Users\Dovydas\source\repos\Solution1\Program1\Client\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\Users\Dovydas\source\repos\Solution1\Program1\node_modules doesn't exist or is not a directory
      C:\Users\Dovydas\source\repos\Solution1\node_modules doesn't exist or is not a directory
      C:\Users\Dovydas\source\repos\node_modules doesn't exist or is not a directory
      C:\Users\Dovydas\source\node_modules doesn't exist or is not a directory
      C:\Users\Dovydas\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules
        using description file: C:\Users\Dovydas\source\repos\Solution1\Program1\Client\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme\package.json (relative path: .)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme is not a file
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme.json doesn't exist
            as directory
              existing directory
                using path: C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme\index
                  using description file: C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme\package.json (relative path: ./index)
                    no extension
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme\index doesn't exist
                    .wasm
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme\index.wasm doesn't exist
                    .mjs
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme\index.mjs doesn't exist
                    .js
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme\index.js doesn't exist
                    .json
                      Field 'browser' doesn't contain a valid alias configuration
                      C:\Users\Dovydas\source\repos\Solution1\Program1\Client\node_modules\devextreme\index.json doesn't exist ]
```

Do you have any ideas how to solve this issue?

Regards,
Dovydas

**Comment by trivialmonster** [comment]
Hi, Did you solve it?

**Comment by sujit510** [comment]
Hey, any updates?

**Comment by rfink** [comment]
Same problem
