### ISSUE TITLE
Cannot be used with node 4

### ISSUE THREAD

**Issue by sudo-suhas** [asfktz/autodll-webpack-plugin#17]
```
λ npm install autodll-webpack-plugin
npm WARN optional dep failed, continuing fsevents@1.1.2

> uglifyjs-webpack-plugin@0.4.6 postinstall E:\Projects\experiments\node_modules\autodll-webpack-plugin\node_modules\webpack\node_modules\uglifyjs-webpack-plugin

> node lib/post_install.js

autodll-webpack-plugin@0.0.7 node_modules\autodll-webpack-plugin
├── bluebird@3.5.0
├── path-to-regexp@1.7.0 (isarray@0.0.1)
├── rmdir@1.2.0 (node.flow@1.2.3)
├── memory-fs@0.4.1 (errno@0.1.4, readable-stream@2.3.3)
├── find-cache-dir@1.0.0 (make-dir@1.0.0, pkg-dir@2.0.0)
├── del@3.0.0 (is-path-cwd@1.0.0, pify@3.0.0, p-map@1.1.1, is-path-in-cwd@1.0.0, globby@6.1.0, rimraf@2.6.1)
└── webpack@3.0.0 (json-loader@0.5.4, tapable@0.2.6, loader-runner@2.3.0, interpret@1.0.3, supports-color@3.2.3, ajv-keywords@2.1.0, loader-utils@1.1.0, enhanced-resolve@3.3.0, webpack-sources@1.0.1, acorn@5.0.3, acorn-dynamic-import@2.0.2, yargs@6.6.0, async@2.5.0, watchpack@1.3.1, uglifyjs-webpack-plugin@0.4.6, ajv@5.2.0, node-libs-browser@2.0.0, escope@3.6.0)

λ node
> require('autodll-webpack-plugin')
E:\Projects\experiments\node_modules\autodll-webpack-plugin\lib\plugin.js:45
  let { entry } = _ref,
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\Projects\experiments\node_modules\autodll-webpack-plugin\lib\index.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by sudo-suhas** [comment]
Why not setup [travis](http://www.codeblocq.com/2016/04/Setup-Travis-CI-with-your-node-project/)?

**Comment by asfktz** [comment]
Merged.

> Why not setup travis?

Yep. That's On my list too
