### ISSUE TITLE
Tests fail if build is not run first

### ISSUE THREAD

**Issue by sudo-suhas** [asfktz/autodll-webpack-plugin#45]
Test files reference `lib` which is created during build. So tests fail like so:
```
module.js:487
    throw err;
    ^
Error: Cannot find module '../lib/createConfig'
  ...
```
This approach has a few disadvantages:
- Changes to source files need to be compiled before it can be tested again. 
- The current git pre-commit hook will not catch issues because build may not have been run after changes to source files.
- If in the future, if you wanted to setup coverage, you wouldn't be able to get accurate reports for your actual source files.

You can assign this issue to me. I'll try to do the needed changes and make a PR by tomorrow.

**Comment by sudo-suhas** [comment]
@asfktz This issue can be closed right? I think you took care of it.

**Comment by sudo-suhas** [comment]
Update:

```
λ rm -rf lib

λ yarn test
yarn run v1.3.2
$ npm run test:unit && npm run test:integration

> autodll-webpack-plugin@0.3.8 test:unit E:\Projects\repos\autodll-webpack-plugin
> ava specs/**/*.spec.js


  15 passed

> autodll-webpack-plugin@0.3.8 test:integration E:\Projects\repos\autodll-webpack-plugin
> node ./scripts/runIntegrationTests.js


> basic@1.0.0 test E:\Projects\repos\autodll-webpack-plugin\specs\fixtures\basic
> ava --serial specs/*.integration.js

module.js:538
    throw err;
    ^

Error: Cannot find module '../../../lib'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Projects\repos\autodll-webpack-plugin\specs\fixtures\basic\webpack.config.js:2:23)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at extensions.(anonymous function) (E:\Projects\repos\autodll-webpack-plugin\specs\fixtures\basic\node_modules\require-precompiled\index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Projects\repos\autodll-webpack-plugin\specs\fixtures\basic\node_modules\ava\lib\process-adapter.js:100:4)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Projects\repos\autodll-webpack-plugin\specs\fixtures\basic\specs\detectPkgChange.integration.js:3:16)
    at Module._compile (module.js:635:30)
module.js:538
    throw err;
    ^

Error: Cannot find module '../../../lib'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Projects\repos\autodll-webpack-plugin\specs\fixtures\basic\webpack.config.js:2:23)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at extensions.(anonymous function) (E:\Projects\repos\autodll-webpack-plugin\specs\fixtures\basic\node_modules\require-precompiled\index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Projects\repos\autodll-webpack-plugin\specs\fixtures\basic\node_modules\ava\lib\process-adapter.js:100:4)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Projects\repos\autodll-webpack-plugin\specs\fixtures\basic\specs\retrieveStats.integration.js:3:16)
    at Module._compile (module.js:635:30)

  2 exceptions

  × specs\detectPkgChange.integration.js exited with a non-zero exit code: 1

  × specs\retrieveStats.integration.js exited with a non-zero exit code: 1
npm ERR! Test failed.  See above for more details.

Integration test for "basic" returned status code 1!

Integration tests are failing!
The following tests returned non-zero status code:
  - basic
```

@asfktz Do you think we should handle this edge case? If I run `build` and try again, there's no problems.
