### ISSUE TITLE
Error: Provided options and query in use

### ISSUE THREAD

**Issue by JimmyLv** [asfktz/autodll-webpack-plugin#47]
```
AutoDllPlugin: is valid cache? true
...\xx-react-scripts\scripts\build.js:21
  throw err;
  ^

Error: Provided options and query in use
    at Function.normalizeUseItem (\xx-react-scripts\node_modules\webpack\lib\RuleSet.js:271:10)
    at Function.normalizeUse (\xx-react-scripts\node_modules\webpack\lib\RuleSet.js:236:19)
    at use.map (\xx-react-scripts\node_modules\webpack\lib\RuleSet.js:233:33)
    at Array.map (native)

```

**Comment by JimmyLv** [comment]
Sorry, I made a mistake in another loader config
