### ISSUE TITLE
Error: no such file or directory

### ISSUE THREAD

**Issue by ClementLoridan** [asfktz/autodll-webpack-plugin#69]
I have this error:
```
    at MemoryFileSystem.writeFileSync (/Users/clementloridan/Workspace/Braineet/agora/node_modules/memory-fs/lib/MemoryFileSystem.js:207:10)
    at /Users/clementloridan/Workspace/Braineet/agora/node_modules/autodll-webpack-plugin/lib/createMemory.js:62:11
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:437:3)
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/assets/js/vendor.js' }
```

**Comment by asfktz** [comment]
Hi, @ClementLoridan
Thanks for reporting.

However, in order to fix it, I need a bit more context.

When do you see this error?
Can you share your webpack config with me?
If you can send me the most minimal config needed to reproduce it I'd appreciate it a lot.

Also will be useful:
- Version of Node
- Version of autodll-webpack-plugin
- Which OS

Thanks!
Asaf

**Comment by ClementLoridan** [comment]
I have this error in my console.

My web pack config client : 

```
import path from 'path';
import webpack from 'webpack';
import merge from 'webpack-merge';
import HappyPack from 'happypack';
import ExtractCssChunks from 'extract-css-chunks-webpack-plugin';
import StatsPlugin from 'stats-webpack-plugin';
import CopyWebpackPlugin from 'copy-webpack-plugin';
import notifier from 'node-notifier';
import base, { isProd, root, src, build, assetsSrc } from '../webpack.config.base.js';

var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

const devEntries = !isProd ? [
    'react-hot-loader/patch',
    'webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000&reload=true)',
] : [];

const devPlugins = [
    new BundleAnalyzerPlugin(),
    new webpack.DllReferencePlugin({
        manifest: path.join(build, "js", "manifest.json")
    }),
    new webpack.NoEmitOnErrorsPlugin(),
    function() {
        this.plugin('done', (stats) => {
            notifier.notify({
                title: 'Webpack : Build Succeeded',
                message: `${stats.compilation.errors.length} Error(s) - ${stats.compilation.warnings.length} Warning(s)`,
                timeout: 2,
            });
        });
        this.plugin('failed', () => {
            notifier.notify({
                title: 'Webpack',
                message: 'Build Failed HARD',
            });
        });
    },
];

const prodPlugins = [
    new webpack.NamedModulesPlugin(),
    new webpack.NamedChunksPlugin((chunk) => {
        if (chunk.name) {
            return chunk.name;
        }

        return chunk.modules.map(m => path.relative(m.context, m.request)).join('_');
    }),
    new webpack.optimize.CommonsChunkPlugin({
        name: 'client',
        async: true,
        children: true,
        minChunks: (module, count) => {
            if (module.resource && (/^.*\.(css|scss)$/).test(module.resource)) {
                return false;
            }
            return count >= 3 && module.context && !module.context.includes('node_modules');
        },
    }),
    new webpack.optimize.CommonsChunkPlugin({
        name: 'client',
        children: true,
        minChunks: module => module.context && module.context.includes('node_modules'),
    }),
    new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor',
        minChunks: module => module.context && module.context.includes('node_modules'),
    }),
    new webpack.optimize.CommonsChunkPlugin({
        name: 'manifest',
        minkChunks: Infinity,
    }),
];


const config = merge(base, {
    name: 'client',
    target: 'web',
    cache: !isProd,
    entry: {
        mainJs: [
            'babel-polyfill/dist/polyfill.js',
            ...devEntries,
            './src/index',
        ]
    },
    output: {
        filename: isProd ? 'js/[name].[chunkhash].js' : 'js/[name].js',
        chunkFilename: isProd ? 'js/[name].[chunkhash].js' : 'js/[name].js',
        path: build,
        publicPath: '/',
        pathinfo: !isProd,
    },
    module: {
        rules: [{
                test: /\.(png|j|jpeg|gif|svg|otf|woff)$/,
                use: ['happypack/loader?id=url'],
            },
            {
                test: /\.(png|j|jpeg|woff|woff2|eot|ttf|otf)$/,
                use: ['happypack/loader?id=files'],
            },
            {
                test: /\.js|\.jsx$/,
                exclude: /node_modules/,
                use: ['happypack/loader?id=js']
            },
            {
                test: /\.pcss$/,
                loaders: ExtractCssChunks.extract({
                    fallback: 'style-loader',
                    use: ['happypack/loader?id=styles']
                }),
            }
        ]
    },
    plugins: [
        new HappyPack({
            id: 'url',
            threads: 4,
            verbose: false,
            loaders: ['url-loader']
        }),
        new HappyPack({
            id: 'files',
            threads: 4,
            verbose: false,
            loaders: ['file-loader']
        }),
        new HappyPack({
            id: 'js',
            threads: 4,
            verbose: false,
            loaders: [{
                loader: 'babel-loader',
                options: {
                    cacheDirectory: !isProd,
                }
            }]
        }),
        new HappyPack({
            id: 'styles',
            threads: 2,
            verbose: false,
            loaders: [{
                    loader: 'css-loader',
                    options: {
                        minimize: isProd,
                        modules: true,
                        importLoaders: 1,
                        localIdentName: isProd ? '[local]_[hash:base64:3]' : '[name]_[local]_[hash:base64:3]',
                    },
                },
                {
                    loader: 'postcss-loader',
                    options: {
                        sourceMap: !isProd,
                        config: {
                            path: 'config/postcss.config.js'
                        }
                    }
                }
            ],
        }),
        ...(isProd ? prodPlugins : devPlugins),
        new StatsPlugin('stats.json'),
        new CopyWebpackPlugin([
            { from: assetsSrc, to: build }
        ]),
        new ExtractCssChunks({
            filename: isProd ? 'css/[name].[chunkhash].css' : 'css/[name].css',
        }),
        new webpack.NormalModuleReplacementPlugin(/desktop\/routes\/SyncRoutes/, 'desktop/routes/AsyncRoutes'),
    ],
});

module.exports = config;
```

The initial product : nothing in particular (index.js, server.js, webpack)

Version:

node v7.6.0
webpack: 3.5.6
autodll-webpack-plugin : the last version
OS : macOS sierra 10.12.5


Voilà

**Comment by waiting4158** [comment]
i have same problem.  has a solution?
mac os: 10.12.6
node:8.7
webpack:3.10.0
webpack-dev-server:2.9.7
memory-fs:0.4.1

**Comment by vladcosorg** [comment]
Can confirm similar issue
