### ISSUE TITLE
bluebird as a dependency

### ISSUE THREAD

**Issue by mario-jerkovic** [asfktz/autodll-webpack-plugin#74]
After updating to any version >= 0.3.x my build config is failing as the `utils.js` has an require to `bluebird` but that package is listed as an devDependency but `mkdirp` is in dependencies

```
Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mariojerkovic/Documents/Projects/.../node_modules/autodll-webpack-plugin/lib/utils/fs.js:8:17)
    at Module._compile (module.js:612:30)
    at Module._extensions..js (module.js:623:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mariojerkovic/Documents/Projects/.../node_modules/babel-watch/runner.js:63:7)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```

**Comment by asfktz** [comment]
Thanks for the reporting *and* providing a solution, @mario-jerkovic!
A released a new version with a fix (0.3.5)
