### ISSUE TITLE
Recommended example doesn't work, pathToArray invalid argument

### ISSUE THREAD

**Issue by codemasterover9000** [asfktz/autodll-webpack-plugin#75]
Pim@AS-DEV06 MINGW64 /c/dev/autodll/examples/recommended (master)
$ npm start

> basic@1.0.0 start C:\dev\autodll\examples\recommended
> webpack-dev-server --history-api-fallback --config ./webpack.config.js

Project is running at http://localhost:8080/
webpack output is served from /
404s will fallback to /index.html
AutoDllPlugin: is valid cache? false
AutoDllPlugin: cleanup
AutoDllPlugin: compile
{ Error: invalid argument
    at pathToArray (C:\dev\autodll\node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)
    at MemoryFileSystem.writeFileSync (C:\dev\autodll\node_modules\memory-fs\lib\MemoryFileSystem.js:200:13)
    at C:\dev\autodll\lib\createMemory.js:62:11
    at tryCatcher (C:\dev\autodll\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\dev\autodll\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\dev\autodll\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\dev\autodll\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\dev\autodll\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\dev\autodll\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (C:\dev\autodll\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (C:\dev\autodll\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\dev\autodll\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\dev\autodll\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
  code: 'EINVAL',
  errno: 18,
  message: 'invalid argument',
  path: '\\assets\\vendor_5526a1788371ac712b7d.js' }

npm version 4.1.2
node version 6.9.4

**Comment by codemasterover9000** [comment]
Seems related to https://github.com/asfktz/autodll-webpack-plugin/pull/71

**Comment by asfktz** [comment]
Hi @codemasterover9000, I've just released a new version with #71, can you please confirm that it works now? thanks

**Comment by codemasterover9000** [comment]
Hi @asfktz sorry for the late reply. It works now.
