### ISSUE TITLE
test 'createMemory should have bundles' failing on Windows

### ISSUE THREAD

**Issue by sudo-suhas** [asfktz/autodll-webpack-plugin#9]
This only affects people looking to contribute to the project. Probably a windows only bug. 

<details>
<summary>Edit: This section of the report is a yarn bug. Ignore.</summary>

Steps:
```
λ rm -rf node_modules\
λ yarn
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ npm run build

> autodll-webpack-plugin@0.0.6 build E:\Projects\repos\autodll-webpack-plugin
> del-cli ./lib && babel src --out-dir lib

src\compileIfNeeded.js -> lib\compileIfNeeded.js
src\createCompiler.js -> lib\createCompiler.js
src\createConfig.js -> lib\createConfig.js
src\createLogger.js -> lib\createLogger.js
src\createMemory.js -> lib\createMemory.js
src\index.js -> lib\index.js
src\normalizeEntry.js -> lib\normalizeEntry.js
src\paths.js -> lib\paths.js
src\plugin.js -> lib\plugin.js
src\utils\fs.js -> lib\utils\fs.js
src\utils\index.js -> lib\utils\index.js
Done in 20.65s.

λ yarn test
yarn test v0.27.5
$ tape -r babel-register specs/**/*.js | faucet
module.js:487
    throw err;
    ^

Error: Cannot find module 'E:\Projects\repos\autodll-webpack-plugin\-r'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at E:\Projects\repos\autodll-webpack-plugin\node_modules\faucet\node_modules\tape\bin\tape:5:5
    at Array.forEach (native)
    at Object.<anonymous> (E:\Projects\repos\autodll-webpack-plugin\node_modules\faucet\node_modules\tape\bin\tape:4:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
not ok 1 no plan found
not ok 2 no assertions found
⨯ fail  2
error Command failed with exit code 1.

λ npm test

> autodll-webpack-plugin@0.0.6 test E:\Projects\repos\autodll-webpack-plugin
> tape -r babel-register specs/**/*.js | faucet

module.js:487
    throw err;
    ^

Error: Cannot find module 'E:\Projects\repos\autodll-webpack-plugin\-r'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at E:\Projects\repos\autodll-webpack-plugin\node_modules\faucet\node_modules\tape\bin\tape:5:5
    at Array.forEach (native)
    at Object.<anonymous> (E:\Projects\repos\autodll-webpack-plugin\node_modules\faucet\node_modules\tape\bin\tape:4:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
not ok 1 no plan found
not ok 2 no assertions found
⨯ fail  2
```

This is probably not an issue with this library though.

</details>

<br>

If I do an `npm install`, the tests run but one fails:
```
λ npm test

> autodll-webpack-plugin@0.0.6 test E:\Projects\repos\autodll-webpack-plugin
> tape -r babel-register specs/**/*.js | faucet

✓ compileIfNeeded: compile: should not call getCompiler when entry is {}
✓ compileIfNeeded: should generate files
✓ compileIfNeeded: should skip when settings equals lastSettings.json
✓ createConfig
# createMemory should have bundles

E:\Projects\repos\autodll-webpack-plugin\node_modules\memory-fs\lib\MemoryFileSystem.js:44
                        throw new MemoryFileSystemError(errors.code.EINVAL, path);
                        ^
Error
    at pathToArray (E:\Projects\repos\autodll-webpack-plugin\node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)
    at MemoryFileSystem.mkdirpSync (E:\Projects\repos\autodll-webpack-plugin\node_modules\memory-fs\lib\MemoryFileSystem.js:139:13)
    at createFakeFS (E:/Projects/repos/autodll-webpack-plugin/specs/createMemory.spec.js:12:6)
    at Test.t (E:/Projects/repos/autodll-webpack-plugin/specs/createMemory.spec.js:20:14)
    at Test.bound [as _cb] (E:\Projects\repos\autodll-webpack-plugin\node_modules\tape\lib\test.js:64:32)
    at Test.run (E:\Projects\repos\autodll-webpack-plugin\node_modules\tape\lib\test.js:83:10)
    at Test.bound [as run] (E:\Projects\repos\autodll-webpack-plugin\node_modules\tape\lib\test.js:64:32)
    at Immediate.next (E:\Projects\repos\autodll-webpack-plugin\node_modules\tape\lib\results.js:71:15)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
✓ createMemory should have bundlesiateCallback] (timers.js:733:5)
not ok 7 no plan found
⨯ fail  1
```

**Comment by sudo-suhas** [comment]
Opened issue upstream - https://github.com/yarnpkg/yarn/issues/3827.

**Comment by sudo-suhas** [comment]
This fails due to `memory-fs` detecting that [`'/my/cache/dir'`](https://github.com/asfktz/autodll-webpack-plugin/blob/master/specs/createMemory.spec.js#L7) which [gets normalized](https://github.com/webpack/memory-fs/blob/master/lib/MemoryFileSystem.js#L28) to `'\my\cache\dir\bundles'` is [not a valid path](https://github.com/webpack/memory-fs/blob/master/lib/MemoryFileSystem.js#L31)) for windows.

Not sure how to fix this. Hopefully there's something wrong only with the test on windows and the functionality is fine.

**Comment by asfktz** [comment]
Hi, @sudo-suhas 
Is this still relevant?

**Comment by sudo-suhas** [comment]
This test still fails on windows.
In addition to that, [this](https://github.com/asfktz/autodll-webpack-plugin/commit/09686900164770665daebb49a901e0136d77de39#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) change is completely breaking the `yarn test` command:
```
$ babel-node ./node_modules/.bin/tape specs/**/*.spec.js | faucet
E:\Projects\repos\autodll-webpack-plugin\node_modules\.bin\tape:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Projects\repos\autodll-webpack-plugin\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (E:\Projects\repos\autodll-webpack-plugin\node_modules\babel-cli\lib\_babel-node.js:154:22)
not ok 1 no plan found
not ok 2 no assertions found
⨯ fail  2
error Command failed with exit code 1.
```

**Comment by sudo-suhas** [comment]
Made PR #38 which solves the `yarn test` failure on windows.

**Comment by asfktz** [comment]
You're awesome as usual, Thanks!

**Comment by sudo-suhas** [comment]
`createMemory should have bundles` still fails on windows. Reopen please?

**Comment by asfktz** [comment]
NP

**Comment by dliu120** [comment]
I am also seeing this failure as well

**Comment by akuznetsov-gridgain** [comment]
Hi, we also need this fix!

**Comment by asfktz** [comment]
Ohhh, can't believe I let this PR wait for so long!
@sudo-suhas, it this still relevant to the current master? Thanks

**Comment by asfktz** [comment]
Ohhh, can't believe I let this PR wait for so long!
@sudo-suhas, it this still relevant to the current master?

**Comment by sudo-suhas** [comment]
I'll test it tomorrow and update here.

**Comment by sudo-suhas** [comment]
As I noted in https://github.com/asfktz/autodll-webpack-plugin/pull/52#issuecomment-343635803, the test is still failing. But now I am not sure if this is a bug in the `specs` or the `src`. See #81.

**Comment by AlexDel** [comment]
Hello guys! We are looking forward for applying you cool lib on our win servers. Is there any stuff I can facilitate with investigation and devloping? We really need this fix :)

**Comment by sudo-suhas** [comment]
Hey @AlexDel, this issue was fixed sometime back but we somehow missed closing it. I am also on a Windows system so I double checked it to be sure and no tests are failing. I'll close the issue as well but if you _do_ happen to face any issue, please open a new one.

> Is there any stuff I can facilitate with investigation and devloping?

Thanks for this though!
